name: Build and Publish syncribullet Docker image

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 6 * * *' # daily at 06:00 UTC
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/syncribullet

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Checkout upstream repo aliyss/syncribullet
        uses: actions/checkout@v4
        with:
          repository: aliyss/syncribullet
          path: upstream
          fetch-depth: 0

      - name: Get upstream commit short SHA
        id: upstream_sha
        run: |
          echo "sha=$(git -C upstream rev-parse --short=12 HEAD)" >> $GITHUB_OUTPUT

      - name: Write Dockerfile (static build via Vite/Qwik)
        working-directory: upstream
        run: |
          cat > Dockerfile <<'EOF'
          FROM node:20-alpine AS build
          WORKDIR /app
          COPY package*.json ./
          RUN npm ci
          COPY . .
          RUN npm run build

          FROM nginx:alpine
          COPY --from=build /app/dist /usr/share/nginx/html
          EXPOSE 80
          CMD ["nginx","-g","daemon off;"]
          EOF

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./upstream
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:upstream-${{ steps.upstream_sha.outputs.sha }}
          provenance: false
